<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RootNamespace>ScoreLab</RootNamespace>
		<LangVersion>default</LangVersion>
		<IsPackable>false</IsPackable>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyName>ScoreLab</AssemblyName>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
	  <EmbeddedResource Remove="Properties\**" />
	  <None Remove="Properties\**" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Include="src\Audio\AudioManager.cs" />
	  <Compile Include="src\Core\API.cs" />
	  <Compile Include="src\Core\HighScoreDefinition.cs" />
	  <Compile Include="src\Core\ScoreDirector.cs" />
	  <Compile Include="src\Core\ScoreTracker.cs" />
	  <Compile Include="src\Core\Settings.cs" />
	  <Compile Include="src\Data\HUDLoader.cs" />
	  <Compile Include="src\Data\JSON\JSONAudioParams.cs" />
	  <Compile Include="src\Data\JSON\JSONHighScore.cs" />
	  <Compile Include="src\Data\JSON\JSONHudManifest.cs" />
	  <Compile Include="src\Data\JSON\JSONMult.cs" />
	  <Compile Include="src\Data\JSON\JSONScore.cs" />
	  <Compile Include="src\Data\MarrowSceneInfo.cs" />
	  <Compile Include="src\Data\Packages\EventType.cs" />
	  <Compile Include="src\Data\Packages\PackedAudioParams.cs" />
	  <Compile Include="src\Data\Packages\PackedHighScore.cs" />
	  <Compile Include="src\Data\Packages\PackedMultiplier.cs" />
	  <Compile Include="src\Data\Packages\PackedScore.cs" />
	  <Compile Include="src\Data\Packages\PackedValue.cs" />
	  <Compile Include="src\Data\ValueManager.cs" />
	  <Compile Include="src\Data\ValuePackage.cs" />
	  <Compile Include="src\HUD\HUDEvents.cs" />
	  <Compile Include="src\HUD\HUDShowMode.cs" />
	  <Compile Include="src\HUD\HUDSpriteText.cs" />
	  <Compile Include="src\HUD\HUDText.cs" />
	  <Compile Include="src\HUD\Modules\HighScoreModule.cs" />
	  <Compile Include="src\Main.cs" />
	  <Compile Include="src\Menu\SLMenu.cs" />
	  <Compile Include="src\Patches\Hooks.cs" />
	  <Compile Include="src\HUD\Modules\Module.cs" />
	  <Compile Include="src\HUD\Modules\ModuleAnimator.cs" />
	  <Compile Include="src\HUD\Modules\MultiplierModule.cs" />
	  <Compile Include="src\HUD\Modules\ScoreModule.cs" />
	  <Compile Include="src\HUD\HUD.cs" />
	  <Compile Include="src\HUD\DescriptorList.cs" />
	  <Compile Include="src\HUD\HUDManager.cs" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="BoneLib">
		  <HintPath>$(BONELAB_DIR)\Mods\BoneLib.dll</HintPath>
		</Reference>
		<Reference Include="NEDebug">
			<HintPath>$(BONELAB_DIR)\Mods\NEDebug.dll</HintPath>
		</Reference>
		<Reference Include="AudioImportLib">
			<HintPath>$(BONELAB_DIR)\Mods\AudioImportLib.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<HintPath>$(BONELAB_DIR)\MelonLoader\net6\Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppRootMotion">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\Il2CppRootMotion.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSLZ.Marrow">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\Il2CppSLZ.Marrow.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Core">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\Il2CppSystem.Core.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\Il2CppSystem.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppUltEvents">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\Il2CppUltEvents.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cpp__Generated">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\Il2Cpp__Generated.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AIModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.AIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AssetBundleModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.AssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.InputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIElementsModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.UIElementsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIElementsNativeModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.UIElementsNativeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.UIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VRModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.VRModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.XRModule">
			<HintPath>$(BONELAB_DIR)\MelonLoader\Il2CppAssemblies\UnityEngine.XRModule.dll</HintPath>
		</Reference>
		<Reference Include="MelonLoader">
			<HintPath>$(BONELAB_DIR)\MelonLoader\net6\MelonLoader.dll</HintPath>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>$(BONELAB_DIR)\MelonLoader\net6\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
			<HintPath>$(BONELAB_DIR)\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Common">
			<HintPath>$(BONELAB_DIR)\MelonLoader\net6\Il2CppInterop.Common.dll</HintPath>
		</Reference>

	</ItemGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>
	
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(BONELAB_DIR)\Mods&quot;" />
	</Target>
</Project>