namespace NEP.ScoreLab.Utilities
{
    public enum CurrentLevel
    {
        MainMenu,
        Theatrigon01,
        Breakroom,
        Museum,
        Streets,
        Runoff,
        SewerStation,
        Warehouse,
        SubwayStation,
        Tower,
        TowerBoss,
        Theatrigon02,
        Dungeon,
        ArenaStory,
        ThroneRoom,
        MuseumBasement,
        Blankbox,
        Tuscany,
        RedactedChamber,
        HandgunBox,
        HoverJunkers,
        FantasyArena,
        ZombieWarehouse,
        MelonVault,
        CustomMap
    }
}
